#!/bin/bash

# ============================================================
# SwarmPit Contributor Script
#
# Let your spare Claude credits work on open issues overnight.
# Two modes:
#   1. SOLVE: Find llm-ready issues, solve them, create PRs
#   2. MODERATE: Clean up messy issues, format them for automation
#
# Usage:
#   ./contribute.sh              # Interactive mode selector
#   ./contribute.sh solve        # Solve llm-ready issues
#   ./contribute.sh moderate     # Format messy issues
#   ./contribute.sh --help       # Show help
#
# Requirements:
#   - claude CLI installed (npm install -g @anthropic-ai/claude-code)
#   - gh CLI installed and authenticated
#   - python3 (for moderate mode)
#   - jq
# ============================================================

set -e

# Config
REPO="${ROBOT_ARENA_REPO:-KKallas/Robot-Arena}"
BRANCH_PREFIX="auto"
MAX_ISSUES=5
ALLOWED_TOOLS="Read,Edit,Write,Glob,Grep,Bash(git *),Bash(grep *),Bash(ls *)"

# Bot signature for all automated content (model can be overridden via env)
CLAUDE_MODEL="${CLAUDE_MODEL:-claude-sonnet-4-20250514}"
BOT_SIGNATURE="

---
🤖 *Generated by SwarmPit Auto-Contributor (Claude $CLAUDE_MODEL)*"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

show_banner() {
    echo ""
    echo -e "${CYAN}============================================${NC}"
    echo -e "${CYAN}  SwarmPit Auto-Contributor${NC}"
    echo -e "${CYAN}  Burning spare Claude credits for good${NC}"
    echo -e "${CYAN}============================================${NC}"
    echo ""
}

show_help() {
    show_banner
    echo "Usage: ./contribute.sh [MODE] [OPTIONS]"
    echo ""
    echo "Modes:"
    echo "  solve      Find llm-ready issues, solve them, create PRs"
    echo "  moderate   Format messy issues for automation"
    echo "  (none)     Interactive mode selector"
    echo ""
    echo "Options:"
    echo "  --max N    Process at most N issues (default: 5)"
    echo "  --dry-run  Show what would be done (no Claude, no GitHub)"
    echo "  --test     Run Claude but don't post to GitHub (safe testing)"
    echo "  --help     Show this help"
    echo ""
    echo "Examples:"
    echo "  ./contribute.sh                       # Interactive"
    echo "  ./contribute.sh solve                 # Solve issues (LIVE)"
    echo "  ./contribute.sh solve --test          # Test solving without PR"
    echo "  ./contribute.sh moderate --dry-run    # Preview issues to moderate"
    echo "  ./contribute.sh moderate --test       # Test moderation without posting"
    echo "  ./contribute.sh moderate --max 3      # Format 3 issues (LIVE)"
    echo ""
}

# Check requirements
check_requirements() {
    echo "Checking requirements..."

    if ! command -v claude &> /dev/null; then
        echo -e "${RED}Error: claude CLI not found${NC}"
        echo "Install with: npm install -g @anthropic-ai/claude-code"
        echo "Then run: claude login"
        exit 1
    fi

    if ! command -v gh &> /dev/null; then
        echo -e "${RED}Error: gh CLI not found${NC}"
        echo "Install from: https://cli.github.com/"
        exit 1
    fi

    if ! command -v jq &> /dev/null; then
        echo -e "${RED}Error: jq not found${NC}"
        echo "Install with: brew install jq (mac) or apt install jq (linux)"
        exit 1
    fi

    # Check if claude is authenticated (either via login or API key)
    if ! claude --version &> /dev/null; then
        echo -e "${RED}Error: claude CLI not working${NC}"
        echo "Run: claude login"
        echo "Or set: export ANTHROPIC_API_KEY=sk-..."
        exit 1
    fi

    # Check gh auth
    if ! gh auth status &> /dev/null; then
        echo -e "${RED}Error: gh not authenticated${NC}"
        echo "Run: gh auth login"
        exit 1
    fi

    echo -e "${GREEN}All requirements met${NC}"
    echo ""
}

# Clone or update repo
setup_repo() {
    WORK_DIR="/tmp/swarmpit-contrib-$$"
    mkdir -p "$WORK_DIR"
    cd "$WORK_DIR"

    echo "Cloning $REPO..."
    gh repo clone "$REPO" repo -- --depth 1
    cd repo

    echo -e "${GREEN}Repo ready at $WORK_DIR/repo${NC}"
    echo ""
}

# Get next llm-ready issue
get_next_issue() {
    echo "Finding next llm-ready issue..."

    ISSUE_JSON=$(gh issue list \
        --repo "$REPO" \
        --label "llm-ready" \
        --state open \
        --limit 1 \
        --json number,title,body)

    ISSUE_NUMBER=$(echo "$ISSUE_JSON" | jq -r '.[0].number // empty')

    if [ -z "$ISSUE_NUMBER" ]; then
        echo -e "${YELLOW}No llm-ready issues found. Nothing to do.${NC}"
        return 1
    fi

    ISSUE_TITLE=$(echo "$ISSUE_JSON" | jq -r '.[0].title')
    ISSUE_BODY=$(echo "$ISSUE_JSON" | jq -r '.[0].body')

    echo -e "${GREEN}Found issue #$ISSUE_NUMBER: $ISSUE_TITLE${NC}"
    echo ""
    return 0
}

# Mark issue as in-progress
claim_issue() {
    if [ "$TEST_MODE" = true ] || [ "$DRY_RUN" = true ]; then
        echo -e "${YELLOW}[TEST] Would claim issue #$ISSUE_NUMBER${NC}"
        echo "  gh issue edit $ISSUE_NUMBER --repo $REPO --add-label in-progress"
        echo "  gh issue comment $ISSUE_NUMBER --repo $REPO --body '🤖 Auto-contributor starting...'"
        return
    fi
    echo "Claiming issue #$ISSUE_NUMBER..."
    gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --add-label "in-progress"
    gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "🤖 Auto-contributor starting work on this issue.$BOT_SIGNATURE"
}

# Release issue if we fail
release_issue() {
    if [ "$TEST_MODE" = true ] || [ "$DRY_RUN" = true ]; then
        echo -e "${YELLOW}[TEST] Would release issue #$ISSUE_NUMBER${NC}"
        echo "  gh issue edit $ISSUE_NUMBER --repo $REPO --remove-label in-progress"
        echo "  gh issue comment $ISSUE_NUMBER --repo $REPO --body 'Error: $1'"
        return
    fi
    echo "Releasing issue #$ISSUE_NUMBER..."
    gh issue edit "$ISSUE_NUMBER" --repo "$REPO" --remove-label "in-progress"
    gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "🤖 Auto-contributor couldn't complete this. Releasing back to queue.

**Error:** $1$BOT_SIGNATURE"
}

# Create branch
create_branch() {
    BRANCH_NAME="${BRANCH_PREFIX}/issue-${ISSUE_NUMBER}"
    git checkout -b "$BRANCH_NAME"
    echo "Created branch: $BRANCH_NAME"
}

# Run Claude on the issue
run_claude() {
    echo ""
    echo "============================================"
    echo "  Running Claude on issue #$ISSUE_NUMBER"
    echo "============================================"
    echo ""

    # Build the prompt
    PROMPT="You are solving a GitHub issue for the SwarmPit project.

## Issue #$ISSUE_NUMBER: $ISSUE_TITLE

$ISSUE_BODY

## Instructions

1. Read all files mentioned in 'Target files'
2. Execute each step in 'Do this' section
3. Verify each checkbox in 'Acceptance Criteria'
4. Run the validation command and confirm it passes
5. When done, summarize what you changed

## Rules

- ONLY modify files listed in 'Target files'
- If something is unclear, make a reasonable choice and note it
- If you cannot complete a step, explain why and stop
- Do NOT create new files unless explicitly told to

Begin by reading the target files, then make the changes."

    # Run claude with -p flag for non-interactive mode
    # --allowedTools auto-approves specific tools without prompting
    if ! claude -p "$PROMPT" --allowedTools "$ALLOWED_TOOLS"; then
        echo -e "${RED}Claude failed${NC}"
        return 1
    fi

    return 0
}

# Check if changes were made
check_changes() {
    if git diff --quiet && git diff --cached --quiet; then
        echo -e "${YELLOW}No changes made by Claude${NC}"
        return 1
    fi

    echo "Changes detected:"
    git status --short
    return 0
}

# Run validation from issue
run_validation() {
    echo ""
    echo "Running validation..."

    # Extract validation command from issue body (between ```bash and ```)
    VALIDATION_CMD=$(echo "$ISSUE_BODY" | sed -n '/```bash/,/```/p' | grep -v '```' | head -20)

    if [ -z "$VALIDATION_CMD" ]; then
        echo -e "${YELLOW}No validation command found in issue${NC}"
        return 0  # Continue anyway
    fi

    echo "Validation command:"
    echo "$VALIDATION_CMD"
    echo ""

    # Run each line
    while IFS= read -r cmd; do
        if [ -n "$cmd" ] && [[ ! "$cmd" =~ ^# ]]; then
            echo "> $cmd"
            if ! eval "$cmd"; then
                echo -e "${YELLOW}Validation command returned non-zero (may be expected)${NC}"
            fi
        fi
    done <<< "$VALIDATION_CMD"

    return 0
}

# Commit and push
commit_and_push() {
    if [ "$TEST_MODE" = true ] || [ "$DRY_RUN" = true ]; then
        echo ""
        echo -e "${YELLOW}[TEST] Would commit and push:${NC}"
        echo "  git add -A"
        echo "  git commit -m '[TASK] $ISSUE_TITLE'"
        echo "  git push -u origin $BRANCH_NAME"
        echo ""
        echo "Changes that would be committed:"
        git status --short
        return
    fi
    echo ""
    echo "Committing changes..."

    git add -A
    git commit -m "[TASK] $ISSUE_TITLE

Closes #$ISSUE_NUMBER

🤖 Generated by SwarmPit Auto-Contributor (Claude claude-sonnet-4-20250514)"

    echo "Pushing to origin..."
    git push -u origin "$BRANCH_NAME"
}

# Create PR
create_pr() {
    if [ "$TEST_MODE" = true ] || [ "$DRY_RUN" = true ]; then
        echo ""
        echo -e "${YELLOW}[TEST] Would create PR:${NC}"
        echo "  Title: [AUTO] $ISSUE_TITLE"
        echo "  Branch: $BRANCH_NAME -> main"
        echo "  Would close issue #$ISSUE_NUMBER"
        echo ""
        echo "Changes that would be in PR:"
        git diff --stat HEAD 2>/dev/null || echo "  (no changes yet)"
        return
    fi
    echo ""
    echo "Creating pull request..."

    PR_BODY="Closes #$ISSUE_NUMBER

## Changes

$(git diff --stat HEAD~1)

## Validation Output

\`\`\`
$(run_validation 2>&1 || true)
\`\`\`

$BOT_SIGNATURE"

    PR_URL=$(gh pr create \
        --repo "$REPO" \
        --title "[AUTO] $ISSUE_TITLE" \
        --body "$PR_BODY" \
        --head "$BRANCH_NAME" \
        --base main)

    echo -e "${GREEN}PR created: $PR_URL${NC}"

    # Comment on issue
    gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body "🤖 PR created: $PR_URL$BOT_SIGNATURE"
}

# Cleanup
cleanup() {
    echo ""
    echo "Cleaning up..."
    cd /
    rm -rf "$WORK_DIR"
}

# Main loop for solve mode
main_solve() {
    check_requirements

    SOLVED=0

    while [ $SOLVED -lt $MAX_ISSUES ]; do
        setup_repo

        if ! get_next_issue; then
            echo "No more issues to process."
            cleanup
            break
        fi

        claim_issue
        create_branch

        if run_claude; then
            if check_changes; then
                if run_validation; then
                    commit_and_push
                    create_pr
                    SOLVED=$((SOLVED + 1))
                    echo -e "${GREEN}Issue #$ISSUE_NUMBER completed!${NC}"
                else
                    release_issue "Validation failed"
                fi
            else
                release_issue "No changes made"
            fi
        else
            release_issue "Claude failed to process"
        fi

        cleanup

        echo ""
        echo "============================================"
        echo "  Completed $SOLVED issues so far"
        echo "============================================"
        echo ""

        # Small delay between issues
        sleep 5
    done

    echo ""
    echo "============================================"
    echo "  Done! Solved $SOLVED issues"
    echo "============================================"
}

# Main for moderate mode
main_moderate() {
    echo "Starting issue moderation..."
    echo ""

    # Check for python3
    if ! command -v python3 &> /dev/null; then
        echo -e "${RED}Error: python3 not found${NC}"
        exit 1
    fi

    # Get the script directory
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Build args
    MODERATE_ARGS=""
    if [ "$DRY_RUN" = true ]; then
        MODERATE_ARGS="$MODERATE_ARGS --dry-run"
    fi
    if [ "$TEST_MODE" = true ]; then
        MODERATE_ARGS="$MODERATE_ARGS --test"
    fi
    if [ -n "$MAX_ISSUES" ]; then
        MODERATE_ARGS="$MODERATE_ARGS --max $MAX_ISSUES"
    fi

    # Run the Python moderator
    python3 "$SCRIPT_DIR/moderate_issues.py" $MODERATE_ARGS
}

# Interactive mode selector
select_mode() {
    show_banner
    echo "What would you like to do?"
    echo ""
    echo -e "  ${GREEN}1) solve${NC}     - Find llm-ready issues and solve them (creates PRs)"
    echo -e "  ${YELLOW}2) moderate${NC}  - Format messy issues for automation (asks questions)"
    echo ""
    read -p "Enter choice [1/2]: " choice

    case $choice in
        1|solve)
            MODE="solve"
            ;;
        2|moderate)
            MODE="moderate"
            ;;
        *)
            echo -e "${RED}Invalid choice${NC}"
            exit 1
            ;;
    esac
}

# Parse arguments
MODE=""
DRY_RUN=false
TEST_MODE=false

while [[ $# -gt 0 ]]; do
    case $1 in
        solve)
            MODE="solve"
            shift
            ;;
        moderate)
            MODE="moderate"
            shift
            ;;
        --max)
            MAX_ISSUES="$2"
            shift 2
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --test)
            TEST_MODE=true
            shift
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# If no mode specified, ask interactively
if [ -z "$MODE" ]; then
    select_mode
fi

# Run the selected mode
show_banner
echo -e "Mode: ${GREEN}$MODE${NC}"
if [ "$DRY_RUN" = true ]; then
    echo -e "⚠️  ${YELLOW}DRY RUN${NC} - No Claude, no GitHub changes"
elif [ "$TEST_MODE" = true ]; then
    echo -e "⚠️  ${YELLOW}TEST MODE${NC} - Claude runs but no GitHub changes"
else
    echo -e "🚀 ${GREEN}LIVE MODE${NC} - Will post to GitHub!"
fi
echo ""

case $MODE in
    solve)
        main_solve
        ;;
    moderate)
        main_moderate
        ;;
esac
