#!/usr/bin/env python3
"""
PR Fixer for MechArena

Finds open PRs with review comments, uses Claude to fix issues based on feedback,
and responds to the comments.

Usage:
    python fix_prs.py              # Process all open PRs with comments
    python fix_prs.py --dry-run    # Show what would be done (no Claude, no GitHub)
    python fix_prs.py --test       # Test mode (runs Claude but doesn't push)
    python fix_prs.py --pr 123     # Process specific PR number

Requirements:
    - gh CLI installed and authenticated
    - claude CLI installed (npm install -g @anthropic-ai/claude-code)
    - git
"""

import subprocess
import json
import sys
import argparse
import os
import tempfile
import shutil
from pathlib import Path

# Config - can override with environment variables
REPO = os.environ.get("MECHARENA_REPO", "KKallas/MechArena")
CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-20250514")
MAX_PRS = 5
ALLOWED_TOOLS_ANALYZE = "Read,Glob,Grep,Bash(ls *)"  # Read-only for analysis
ALLOWED_TOOLS_FIX = "Read,Edit,Write,Glob,Grep,Bash(git *),Bash(grep *),Bash(ls *)"  # Full access for fixing

# Bot signature for all automated content
BOT_SIGNATURE = f"""

---
🤖 *Generated by SwarmPit PR Fixer (Claude {CLAUDE_MODEL})*"""

# Label to remove when needs human attention
NEEDS_ATTENTION_LABEL = "llm-ready"


def run_cmd(cmd: list[str], check: bool = True, cwd: str = None) -> subprocess.CompletedProcess:
    """Run a command and return result."""
    return subprocess.run(cmd, capture_output=True, text=True, check=check, cwd=cwd)


def check_requirements() -> bool:
    """Check if required tools are installed."""
    missing = []

    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("gh", "Install from: https://cli.github.com/"))
    except subprocess.CalledProcessError:
        missing.append(("gh", "Run: gh auth login"))

    try:
        subprocess.run(["claude", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("claude", "Install with: npm install -g @anthropic-ai/claude-code"))

    try:
        subprocess.run(["git", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("git", "Install git"))

    if missing:
        print("\n❌ Missing requirements:")
        for tool, fix in missing:
            print(f"  - {tool}: {fix}")
        print("")
        return False

    return True


def get_open_prs_with_comments() -> list[dict]:
    """Get all open PRs that have review comments."""
    # Get open PRs
    result = run_cmd([
        "gh", "pr", "list",
        "--repo", REPO,
        "--state", "open",
        "--json", "number,title,headRefName,body,labels"
    ], check=False)

    if result.returncode != 0:
        print(f"\n❌ Failed to fetch PRs from GitHub:")
        print(f"  {result.stderr.strip()}")
        sys.exit(1)

    prs = json.loads(result.stdout)

    # Filter to only PRs with pending review comments
    prs_with_comments = []
    for pr in prs:
        # Check if PR has review comments that need addressing
        comments = get_pr_comments(pr['number'])
        if comments:
            pr['review_comments'] = comments
            pr['diff'] = get_pr_diff(pr['number'])
            prs_with_comments.append(pr)

    return prs_with_comments


def get_pr_comments(pr_number: int) -> list[dict]:
    """Get all comments on a PR (both inline review and general comments)."""
    actionable = []

    # Get inline review comments (code-specific)
    result = run_cmd([
        "gh", "api",
        f"repos/{REPO}/pulls/{pr_number}/comments",
        "--jq", "."
    ], check=False)

    if result.returncode == 0:
        comments = json.loads(result.stdout)
        for c in comments:
            if "🤖" in c.get("body", ""):
                continue
            actionable.append({
                "id": c["id"],
                "type": "review",
                "path": c.get("path", ""),
                "line": c.get("line") or c.get("original_line"),
                "body": c["body"],
                "author": c.get("user", {}).get("login", "unknown"),
                "diff_hunk": c.get("diff_hunk", "")
            })

    # Get general PR comments (issue-style comments)
    result = run_cmd([
        "gh", "api",
        f"repos/{REPO}/issues/{pr_number}/comments",
        "--jq", "."
    ], check=False)

    if result.returncode == 0:
        comments = json.loads(result.stdout)
        for c in comments:
            if "🤖" in c.get("body", ""):
                continue
            actionable.append({
                "id": c["id"],
                "type": "issue",
                "path": "",
                "line": None,
                "body": c["body"],
                "author": c.get("user", {}).get("login", "unknown"),
                "diff_hunk": ""
            })

    return actionable


def get_pr(pr_number: int) -> dict:
    """Get a specific PR with its review comments and diff."""
    result = run_cmd([
        "gh", "pr", "view", str(pr_number),
        "--repo", REPO,
        "--json", "number,title,headRefName,body,labels,baseRefName"
    ])
    pr = json.loads(result.stdout)
    pr['review_comments'] = get_pr_comments(pr_number)
    pr['diff'] = get_pr_diff(pr_number)
    return pr


def setup_repo(work_dir: str, branch: str) -> str:
    """Clone repo and checkout the PR branch."""
    print(f"Cloning {REPO} to {work_dir}...")
    run_cmd(["gh", "repo", "clone", REPO, "repo"], cwd=work_dir)
    repo_dir = os.path.join(work_dir, "repo")

    print(f"Checking out branch {branch}...")
    run_cmd(["git", "fetch", "origin", branch], cwd=repo_dir)
    run_cmd(["git", "checkout", branch], cwd=repo_dir)

    return repo_dir


def get_pr_diff(pr_number: int) -> str:
    """Get the full diff for a PR."""
    result = run_cmd([
        "gh", "pr", "diff", str(pr_number),
        "--repo", REPO
    ], check=False)

    if result.returncode != 0:
        return "(Could not fetch diff)"

    # Limit diff size to avoid huge prompts
    diff = result.stdout
    if len(diff) > 15000:
        diff = diff[:15000] + "\n\n... (diff truncated, too large) ..."

    return diff


def format_comments(pr: dict) -> str:
    """Format comments for prompts."""
    comments_text = ""
    for c in pr.get('review_comments', []):
        if c.get('type') == 'review' and c.get('path'):
            comments_text += f"""
### Inline comment by @{c['author']} on `{c['path']}` (line {c['line']}):
```
{c['diff_hunk']}
```
**Feedback:** {c['body']}

"""
        else:
            comments_text += f"""
### General comment by @{c['author']}:
**Feedback:** {c['body']}

"""
    return comments_text


def build_analysis_prompt(pr: dict) -> str:
    """Build prompt to analyze if feedback is actionable."""
    comments_text = format_comments(pr)
    diff = pr.get('diff', '(no diff available)')

    return f"""You are analyzing review feedback on a pull request to determine if it's actionable.

## PR #{pr['number']}: {pr['title']}

Branch: {pr['headRefName']}

## PR Diff (what this PR changes)

```diff
{diff}
```

## Review Comments

{comments_text}

## Your Task

Analyze each comment and determine:
1. Is the feedback specific enough to act on?
2. Are target files/locations clear (either explicitly stated or inferable from context)?
3. Is the requested change clear?

Use the diff above to understand what code was added/removed. Lines starting with `-` were removed, lines starting with `+` were added.

## Response Format

You MUST respond with EXACTLY ONE of these two formats:

**If actionable:**
```
ACTIONABLE: YES
SUMMARY: [1-2 sentence summary of what needs to be done]
```

**If needs clarification:**
```
ACTIONABLE: NO
QUESTIONS:
- [Specific question 1]
- [Specific question 2]
```

## Rules

- Be generous - if you can reasonably infer what's needed, it's actionable
- Only say NO if the feedback is genuinely unclear or ambiguous
- Questions should be specific, not generic

Analyze the feedback now."""


def build_fix_prompt(pr: dict) -> str:
    """Build the prompt for Claude to fix PR issues."""
    comments_text = format_comments(pr)
    diff = pr.get('diff', '(no diff available)')

    return f"""You are fixing a pull request based on review feedback.

## PR #{pr['number']}: {pr['title']}

Branch: {pr['headRefName']}

## PR Diff (what this PR currently changes)

```diff
{diff}
```

## Review Comments to Address

{comments_text}

## Instructions

1. Read each comment and understand what change is requested
2. Look at the diff to understand what was already changed in this PR
3. Make the requested changes to the files
4. Be precise - only change what's requested, don't refactor unrelated code
5. After making changes, summarize what you fixed

## Rules

- Address EACH comment - don't skip any
- If a comment is unclear, make a reasonable interpretation and note it
- Keep changes minimal and focused
- The reviewer may be referring to code that was removed (lines with `-`) or added (lines with `+`) in the diff

Begin by reading the files mentioned in the comments, then make the fixes."""


def run_claude(prompt: str, repo_dir: str, allowed_tools: str, capture_output: bool = False) -> tuple[bool, str]:
    """Run Claude on the PR. Returns (success, output_text)."""
    print(f"\n--- Claude output (streaming) ---")
    sys.stdout.flush()

    output_text = ""

    try:
        process = subprocess.Popen(
            ["claude", "-p", prompt, "--allowedTools", allowed_tools,
             "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            cwd=repo_dir
        )

        for line in process.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
                if event.get("type") == "assistant":
                    content = event.get("message", {}).get("content", [])
                    for block in content:
                        if block.get("type") == "text":
                            text = block.get("text", "")
                            print(text, end="", flush=True)
                            if capture_output:
                                output_text += text
                elif event.get("type") == "content_block_delta":
                    delta = event.get("delta", {})
                    if delta.get("type") == "text_delta":
                        text = delta.get("text", "")
                        print(text, end="", flush=True)
                        if capture_output:
                            output_text += text
                elif event.get("type") == "result":
                    result = event.get("result", "")
                    if result and isinstance(result, str):
                        print(result, flush=True)
                        if capture_output:
                            output_text += result
            except json.JSONDecodeError:
                print(line, flush=True)

        process.wait()

        stderr_output = process.stderr.read()
        if stderr_output:
            print(f"\n[stderr]: {stderr_output}", flush=True)

        print(f"\n--- End output ---")

        return process.returncode == 0, output_text

    except Exception as e:
        print(f"Error running Claude: {e}")
        return False, ""


def parse_analysis_result(output: str) -> tuple[bool, str]:
    """Parse the analysis output to determine if actionable."""
    # Look for ACTIONABLE: YES or NO
    output_upper = output.upper()

    if "ACTIONABLE: YES" in output_upper:
        # Extract summary if present
        lines = output.split("\n")
        for line in lines:
            if line.upper().startswith("SUMMARY:"):
                return True, line[8:].strip()
        return True, "Feedback is actionable"

    elif "ACTIONABLE: NO" in output_upper:
        # Extract questions
        questions = []
        in_questions = False
        for line in output.split("\n"):
            if "QUESTIONS:" in line.upper():
                in_questions = True
                continue
            if in_questions and line.strip().startswith("-"):
                questions.append(line.strip()[1:].strip())

        return False, "\n".join(f"- {q}" for q in questions) if questions else "Feedback needs clarification"

    # Default to actionable if we can't parse (be generous)
    return True, "Could not parse analysis, proceeding with fix"


def request_clarification(pr: dict, questions: str, dry_run: bool = False, test_mode: bool = False):
    """Post a comment asking for clarification and remove llm-ready label."""
    comment_body = f"""I'd like to address this feedback, but need some clarification:

{questions}

Please provide more details so I can make the requested changes.{BOT_SIGNATURE}"""

    if dry_run or test_mode:
        print(f"\n[TEST] Would post clarification request:")
        print(comment_body)
        print(f"\n[TEST] Would remove label: {NEEDS_ATTENTION_LABEL}")
        return

    # Post comment
    run_cmd([
        "gh", "pr", "comment", str(pr['number']),
        "--repo", REPO,
        "--body", comment_body
    ], check=False)
    print(f"  Posted clarification request")

    # Remove llm-ready label to signal human attention needed
    run_cmd([
        "gh", "pr", "edit", str(pr['number']),
        "--repo", REPO,
        "--remove-label", NEEDS_ATTENTION_LABEL
    ], check=False)
    print(f"  Removed {NEEDS_ATTENTION_LABEL} label")


def check_changes(repo_dir: str) -> bool:
    """Check if Claude made any changes."""
    result = run_cmd(["git", "status", "--porcelain"], cwd=repo_dir)
    if not result.stdout.strip():
        print("No changes made by Claude")
        return False

    print("Changes detected:")
    print(result.stdout)
    return True


def commit_and_push(pr: dict, repo_dir: str, dry_run: bool = False, test_mode: bool = False) -> bool:
    """Commit changes and push to the PR branch."""
    if dry_run or test_mode:
        print(f"\n[TEST] Would commit and push fixes:")
        result = run_cmd(["git", "diff", "--stat"], cwd=repo_dir)
        print(result.stdout)
        return True

    print("\nCommitting fixes...")
    run_cmd(["git", "add", "-A"], cwd=repo_dir)

    commit_msg = f"""Address review feedback on PR #{pr['number']}

🤖 Generated by SwarmPit PR Fixer (Claude {CLAUDE_MODEL})"""

    run_cmd(["git", "commit", "-m", commit_msg], cwd=repo_dir)

    print("Pushing to origin...")
    run_cmd(["git", "push"], cwd=repo_dir)

    return True


def reply_to_comments(pr: dict, dry_run: bool = False, test_mode: bool = False):
    """Reply to each comment indicating it's been addressed."""
    if dry_run or test_mode:
        print(f"\n[TEST] Would reply to {len(pr.get('review_comments', []))} comments")
        return

    for comment in pr.get('review_comments', []):
        reply_body = f"Addressed in latest commit.{BOT_SIGNATURE}"

        if comment.get('type') == 'review':
            # Reply to inline review comment
            run_cmd([
                "gh", "api",
                f"repos/{REPO}/pulls/{pr['number']}/comments/{comment['id']}/replies",
                "-f", f"body={reply_body}"
            ], check=False)
        else:
            # Reply to general issue comment
            run_cmd([
                "gh", "api",
                f"repos/{REPO}/issues/{pr['number']}/comments",
                "-f", f"body={reply_body}"
            ], check=False)

        print(f"  Replied to comment {comment['id']}")


def process_pr(pr: dict, dry_run: bool = False, test_mode: bool = False) -> bool:
    """Process a single PR."""
    print(f"\n{'='*60}")
    print(f"Processing PR #{pr['number']}: {pr['title']}")
    if test_mode:
        print(f"⚠️  TEST MODE - Claude runs but no push")
    elif dry_run:
        print(f"⚠️  DRY RUN - Nothing will be executed")
    print(f"{'='*60}")

    comments = pr.get('review_comments', [])
    print(f"\nPR details:")
    print(f"  Number: #{pr['number']}")
    print(f"  Title: {pr['title']}")
    print(f"  Branch: {pr['headRefName']}")
    print(f"  Review comments: {len(comments)}")

    for c in comments:
        print(f"    - {c['path']}:{c['line']} by @{c['author']}")

    if dry_run:
        print(f"\n[DRY RUN] Would process this PR")
        return True

    if not comments:
        print("No review comments to address")
        return True

    # Create temp directory for work
    work_dir = tempfile.mkdtemp(prefix="swarmpit-pr-")

    try:
        # Clone and checkout PR branch
        repo_dir = setup_repo(work_dir, pr['headRefName'])

        # PHASE 1: Analyze if feedback is actionable
        print("\n📋 Phase 1: Analyzing feedback...")
        analysis_prompt = build_analysis_prompt(pr)
        success, analysis_output = run_claude(analysis_prompt, repo_dir, ALLOWED_TOOLS_ANALYZE, capture_output=True)

        if not success:
            print("Claude failed to analyze")
            return False

        is_actionable, details = parse_analysis_result(analysis_output)

        if not is_actionable:
            print(f"\n⚠️  Feedback needs clarification")
            print(f"Questions: {details}")
            request_clarification(pr, details, dry_run, test_mode)
            print(f"\n🔄 PR #{pr['number']} - requested clarification, removed {NEEDS_ATTENTION_LABEL} label")
            return True  # Successfully handled, just not by fixing

        print(f"\n✅ Feedback is actionable: {details}")

        # PHASE 2: Make the fixes
        print("\n🔧 Phase 2: Making fixes...")
        fix_prompt = build_fix_prompt(pr)
        success, _ = run_claude(fix_prompt, repo_dir, ALLOWED_TOOLS_FIX, capture_output=False)

        if not success:
            print("Claude failed to fix")
            return False

        # Check if changes were made
        if not check_changes(repo_dir):
            print("No changes needed or Claude couldn't fix the issues")
            return False

        # Commit and push
        if not commit_and_push(pr, repo_dir, dry_run, test_mode):
            return False

        # Reply to comments
        reply_to_comments(pr, dry_run, test_mode)

        print(f"\n✅ PR #{pr['number']} fixes pushed!")
        return True

    except Exception as e:
        print(f"Error processing PR: {e}")
        return False

    finally:
        print(f"\nCleaning up {work_dir}...")
        shutil.rmtree(work_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(
        description="Fix PRs based on review comments",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Modes:
  (default)   Run Claude, push fixes, reply to comments
  --test      Run Claude but DON'T push
  --dry-run   Don't run Claude at all, just show what would happen

Examples:
  python fix_prs.py --dry-run        # Preview PRs to process
  python fix_prs.py --test --pr 123  # Test Claude on PR #123
  python fix_prs.py --pr 123         # Actually fix PR #123
        """
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be done without running Claude")
    parser.add_argument("--test", action="store_true",
                        help="Run Claude but don't push or reply")
    parser.add_argument("--pr", type=int,
                        help="Process a specific PR number")
    parser.add_argument("--max", type=int, default=MAX_PRS,
                        help=f"Max PRs to process (default: {MAX_PRS})")
    args = parser.parse_args()

    print("=" * 60)
    print("  MechArena PR Fixer")
    print("  Fixing PRs based on review feedback")
    print("=" * 60)

    if args.dry_run:
        print("\n⚠️  DRY RUN MODE - No Claude, no GitHub changes")
    elif args.test:
        print("\n⚠️  TEST MODE - Claude runs but no push")
    else:
        print("\n🚀 LIVE MODE - Will push fixes!")

    if not check_requirements():
        sys.exit(1)

    if args.pr:
        pr = get_pr(args.pr)
        if not pr.get('review_comments'):
            print(f"\n✅ PR #{args.pr} has no review comments to address")
            return
        process_pr(pr, dry_run=args.dry_run, test_mode=args.test)
    else:
        prs = get_open_prs_with_comments()

        if not prs:
            print("\n✅ No PRs with review comments. Nothing to fix!")
            return

        print(f"\nFound {len(prs)} PRs with review comments:")
        for pr in prs[:args.max]:
            comments = pr.get('review_comments', [])
            print(f"  #{pr['number']}: {pr['title']} ({len(comments)} comments)")

        if len(prs) > args.max:
            print(f"  ... and {len(prs) - args.max} more (use --max to increase)")

        print("")

        fixed = 0
        for pr in prs[:args.max]:
            if process_pr(pr, dry_run=args.dry_run, test_mode=args.test):
                fixed += 1
            else:
                print(f"⚠️  Failed to fix PR #{pr['number']}")

        print(f"\n{'='*60}")
        print(f"  Done! Fixed {fixed}/{min(len(prs), args.max)} PRs")
        print(f"{'='*60}")


if __name__ == "__main__":
    main()
