#!/usr/bin/env python3
"""
Issue Solver for Robot Arena

Finds llm-ready issues, uses Claude to solve them, and creates PRs.

Usage:
    python solve_issues.py              # Process all llm-ready issues
    python solve_issues.py --dry-run    # Show what would be done (no Claude, no GitHub)
    python solve_issues.py --test       # Test mode (runs Claude but doesn't push/PR)
    python solve_issues.py --issue 123  # Process specific issue

Requirements:
    - gh CLI installed and authenticated
    - claude CLI installed (npm install -g @anthropic-ai/claude-code)
    - git
"""

import subprocess
import json
import sys
import argparse
import os
import tempfile
import shutil
from pathlib import Path

# Config - can override with environment variables
REPO = os.environ.get("ROBOT_ARENA_REPO", "KKallas/Robot-Arena")
CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-20250514")
MAX_ISSUES = 5
BRANCH_PREFIX = "auto"
ALLOWED_TOOLS = "Read,Edit,Write,Glob,Grep,Bash(git *),Bash(grep *),Bash(ls *)"

# Bot signature for all automated content
BOT_SIGNATURE = f"""

---
🤖 *Generated by SwarmPit Auto-Contributor (Claude {CLAUDE_MODEL})*"""


def run_cmd(cmd: list[str], check: bool = True, cwd: str = None) -> subprocess.CompletedProcess:
    """Run a command and return result."""
    return subprocess.run(cmd, capture_output=True, text=True, check=check, cwd=cwd)


def check_requirements() -> bool:
    """Check if required tools are installed."""
    missing = []

    # Check gh CLI
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("gh", "Install from: https://cli.github.com/"))
    except subprocess.CalledProcessError:
        missing.append(("gh", "Run: gh auth login"))

    # Check claude CLI
    try:
        subprocess.run(["claude", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("claude", "Install with: npm install -g @anthropic-ai/claude-code"))

    # Check git
    try:
        subprocess.run(["git", "--version"], capture_output=True, check=True)
    except FileNotFoundError:
        missing.append(("git", "Install git"))

    if missing:
        print("\n❌ Missing requirements:")
        for tool, fix in missing:
            print(f"  - {tool}: {fix}")
        print("")
        return False

    return True


def get_llm_ready_issues() -> list[dict]:
    """Get all issues with llm-ready label."""
    result = run_cmd([
        "gh", "issue", "list",
        "--repo", REPO,
        "--label", "llm-ready",
        "--state", "open",
        "--limit", "100",
        "--json", "number,title,body,labels"
    ], check=False)

    if result.returncode != 0:
        print(f"\n❌ Failed to fetch issues from GitHub:")
        print(f"  {result.stderr.strip()}")
        print(f"\nTry running: gh auth login")
        sys.exit(1)

    issues = json.loads(result.stdout)

    # Filter out in-progress issues
    filtered = []
    for issue in issues:
        label_names = [l["name"] for l in issue.get("labels", [])]
        if "in-progress" not in label_names:
            filtered.append(issue)

    return filtered


def get_issue(issue_number: int) -> dict:
    """Get a specific issue."""
    result = run_cmd([
        "gh", "issue", "view", str(issue_number),
        "--repo", REPO,
        "--json", "number,title,body,labels"
    ])
    return json.loads(result.stdout)


def claim_issue(issue_number: int, dry_run: bool = False, test_mode: bool = False):
    """Mark issue as in-progress."""
    if dry_run or test_mode:
        print(f"[TEST] Would claim issue #{issue_number}")
        print(f"  gh issue edit {issue_number} --repo {REPO} --add-label in-progress")
        return

    print(f"Claiming issue #{issue_number}...")
    run_cmd(["gh", "issue", "edit", str(issue_number), "--repo", REPO, "--add-label", "in-progress"])
    run_cmd([
        "gh", "issue", "comment", str(issue_number),
        "--repo", REPO,
        "--body", f"🤖 Auto-contributor starting work on this issue.{BOT_SIGNATURE}"
    ])


def release_issue(issue_number: int, error: str, dry_run: bool = False, test_mode: bool = False):
    """Release issue back to queue."""
    if dry_run or test_mode:
        print(f"[TEST] Would release issue #{issue_number}")
        return

    print(f"Releasing issue #{issue_number}...")
    run_cmd(["gh", "issue", "edit", str(issue_number), "--repo", REPO, "--remove-label", "in-progress"])
    run_cmd([
        "gh", "issue", "comment", str(issue_number),
        "--repo", REPO,
        "--body", f"🤖 Auto-contributor couldn't complete this. Releasing back to queue.\n\n**Error:** {error}{BOT_SIGNATURE}"
    ])


def setup_repo(work_dir: str) -> str:
    """Clone repo to work directory."""
    print(f"Cloning {REPO} to {work_dir}...")
    run_cmd(["gh", "repo", "clone", REPO, "repo", "--", "--depth", "1"], cwd=work_dir)
    return os.path.join(work_dir, "repo")


def build_prompt(issue: dict) -> str:
    """Build the prompt for Claude."""
    return f"""You are solving a GitHub issue for the Robot Arena project.

## Issue #{issue['number']}: {issue['title']}

{issue['body']}

## Instructions

1. Read all files mentioned in 'Target files'
2. Execute each step in 'Do this' section
3. Verify each checkbox in 'Acceptance Criteria'
4. Run the validation command and confirm it passes
5. When done, summarize what you changed

## Rules

- ONLY modify files listed in 'Target files'
- If something is unclear, make a reasonable choice and note it
- If you cannot complete a step, explain why and stop
- Do NOT create new files unless explicitly told to

Begin by reading the target files, then make the changes."""


def run_claude(prompt: str, repo_dir: str, test_mode: bool = False) -> bool:
    """Run Claude on the issue."""
    print(f"\n--- Claude output (streaming) ---")
    sys.stdout.flush()

    try:
        # Use stream-json for real-time streaming output (requires --verbose)
        # --dangerously-skip-permissions allows commands without interactive approval
        process = subprocess.Popen(
            ["claude", "-p", prompt, "--allowedTools", ALLOWED_TOOLS, "--output-format", "stream-json", "--verbose", "--dangerously-skip-permissions"],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            cwd=repo_dir
        )

        # Parse streaming JSON and print text content in real-time
        for line in process.stdout:
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
                # Handle different event types from stream-json
                if event.get("type") == "assistant":
                    content = event.get("message", {}).get("content", [])
                    for block in content:
                        if block.get("type") == "text":
                            print(block.get("text", ""), end="", flush=True)
                elif event.get("type") == "content_block_delta":
                    delta = event.get("delta", {})
                    if delta.get("type") == "text_delta":
                        print(delta.get("text", ""), end="", flush=True)
                elif event.get("type") == "result":
                    result = event.get("result", "")
                    if result and isinstance(result, str):
                        print(result, flush=True)
            except json.JSONDecodeError:
                # If not valid JSON, just print as-is
                print(line, flush=True)

        process.wait()
        print(f"\n--- End output ---")

        return process.returncode == 0

    except Exception as e:
        print(f"Error running Claude: {e}")
        return False


def check_changes(repo_dir: str) -> bool:
    """Check if Claude made any changes."""
    result = run_cmd(["git", "status", "--porcelain"], cwd=repo_dir)
    if not result.stdout.strip():
        print("No changes made by Claude")
        return False

    print("Changes detected:")
    print(result.stdout)
    return True


def run_validation(issue: dict, repo_dir: str) -> bool:
    """Run validation commands from issue body."""
    body = issue.get("body", "")

    # Extract bash commands between ```bash and ```
    import re
    matches = re.findall(r'```bash\n(.*?)```', body, re.DOTALL)

    if not matches:
        print("No validation commands found in issue")
        return True

    print("\nRunning validation...")
    for cmd_block in matches:
        for line in cmd_block.strip().split('\n'):
            line = line.strip()
            if line and not line.startswith('#'):
                print(f"> {line}")
                result = run_cmd(["bash", "-c", line], check=False, cwd=repo_dir)
                print(result.stdout)
                if result.stderr:
                    print(result.stderr)

    return True


def commit_and_push(issue: dict, repo_dir: str, dry_run: bool = False, test_mode: bool = False) -> str:
    """Commit changes and push to remote."""
    branch_name = f"{BRANCH_PREFIX}/issue-{issue['number']}"

    if dry_run or test_mode:
        print(f"\n[TEST] Would commit and push:")
        print(f"  Branch: {branch_name}")
        result = run_cmd(["git", "status", "--short"], cwd=repo_dir)
        print(f"  Changes:\n{result.stdout}")
        return branch_name

    print(f"\nCreating branch {branch_name}...")
    run_cmd(["git", "checkout", "-b", branch_name], cwd=repo_dir)

    print("Committing changes...")
    run_cmd(["git", "add", "-A"], cwd=repo_dir)

    commit_msg = f"""[TASK] {issue['title']}

Closes #{issue['number']}

🤖 Generated by SwarmPit Auto-Contributor (Claude {CLAUDE_MODEL})"""

    run_cmd(["git", "commit", "-m", commit_msg], cwd=repo_dir)

    print("Pushing to origin...")
    run_cmd(["git", "push", "-u", "origin", branch_name], cwd=repo_dir)

    return branch_name


def create_pr(issue: dict, branch_name: str, repo_dir: str, dry_run: bool = False, test_mode: bool = False) -> str:
    """Create a pull request."""
    if dry_run or test_mode:
        print(f"\n[TEST] Would create PR:")
        print(f"  Title: [AUTO] {issue['title']}")
        print(f"  Branch: {branch_name} -> main")
        return "https://github.com/test/pr"

    print("\nCreating pull request...")

    # Get diff stats
    result = run_cmd(["git", "diff", "--stat", "HEAD~1"], cwd=repo_dir, check=False)
    diff_stats = result.stdout if result.returncode == 0 else "(no stats)"

    pr_body = f"""Closes #{issue['number']}

## Changes

{diff_stats}
{BOT_SIGNATURE}"""

    result = run_cmd([
        "gh", "pr", "create",
        "--repo", REPO,
        "--title", f"[AUTO] {issue['title']}",
        "--body", pr_body,
        "--head", branch_name,
        "--base", "main"
    ], cwd=repo_dir)

    pr_url = result.stdout.strip()
    print(f"PR created: {pr_url}")

    # Comment on issue
    run_cmd([
        "gh", "issue", "comment", str(issue['number']),
        "--repo", REPO,
        "--body", f"🤖 PR created: {pr_url}{BOT_SIGNATURE}"
    ])

    return pr_url


def process_issue(issue: dict, dry_run: bool = False, test_mode: bool = False) -> bool:
    """Process a single issue."""
    print(f"\n{'='*60}")
    print(f"Processing issue #{issue['number']}: {issue['title']}")
    if test_mode:
        print(f"⚠️  TEST MODE - Claude runs but no push/PR")
    elif dry_run:
        print(f"⚠️  DRY RUN - Nothing will be executed")
    print(f"{'='*60}")

    # Show issue details
    labels = [l["name"] for l in issue.get("labels", [])]
    print(f"\nIssue details:")
    print(f"  Number: #{issue['number']}")
    print(f"  Title: {issue['title']}")
    print(f"  Labels: {', '.join(labels) if labels else 'none'}")
    print(f"  Body length: {len(issue.get('body', '') or '')} chars")

    if dry_run:
        print(f"\n[DRY RUN] Would process this issue")
        return True

    # Create temp directory for work
    work_dir = tempfile.mkdtemp(prefix="swarmpit-")

    try:
        # Claim the issue
        claim_issue(issue['number'], dry_run, test_mode)

        # Clone repo
        repo_dir = setup_repo(work_dir)

        # Build prompt and run Claude
        prompt = build_prompt(issue)
        if not run_claude(prompt, repo_dir, test_mode):
            release_issue(issue['number'], "Claude failed to process", dry_run, test_mode)
            return False

        # Check if changes were made
        if not check_changes(repo_dir):
            release_issue(issue['number'], "No changes made", dry_run, test_mode)
            return False

        # Run validation
        run_validation(issue, repo_dir)

        # Commit and push
        branch_name = commit_and_push(issue, repo_dir, dry_run, test_mode)

        # Create PR
        create_pr(issue, branch_name, repo_dir, dry_run, test_mode)

        print(f"\n✅ Issue #{issue['number']} completed!")
        return True

    except Exception as e:
        print(f"Error processing issue: {e}")
        release_issue(issue['number'], str(e), dry_run, test_mode)
        return False

    finally:
        # Cleanup
        print(f"\nCleaning up {work_dir}...")
        shutil.rmtree(work_dir, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(
        description="Solve GitHub issues for Robot Arena",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Modes:
  (default)   Run Claude, push changes, create PR
  --test      Run Claude but DON'T push or create PR
  --dry-run   Don't run Claude at all, just show what would happen

Examples:
  python solve_issues.py --dry-run           # Preview issues to process
  python solve_issues.py --test --issue 123  # Test Claude on issue #123
  python solve_issues.py --issue 123         # Actually solve issue #123
        """
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be done without running Claude")
    parser.add_argument("--test", action="store_true",
                        help="Run Claude but don't push or create PR")
    parser.add_argument("--issue", type=int,
                        help="Process a specific issue number")
    parser.add_argument("--max", type=int, default=MAX_ISSUES,
                        help=f"Max issues to process (default: {MAX_ISSUES})")
    args = parser.parse_args()

    print("=" * 60)
    print("  Robot Arena Issue Solver")
    print("  Solving llm-ready issues and creating PRs")
    print("=" * 60)

    if args.dry_run:
        print("\n⚠️  DRY RUN MODE - No Claude, no GitHub changes")
    elif args.test:
        print("\n⚠️  TEST MODE - Claude runs but no push/PR")
    else:
        print("\n🚀 LIVE MODE - Will push and create PRs!")

    # Check requirements
    if not check_requirements():
        sys.exit(1)

    if args.issue:
        # Process specific issue
        issue = get_issue(args.issue)
        process_issue(issue, dry_run=args.dry_run, test_mode=args.test)
    else:
        # Process all llm-ready issues
        issues = get_llm_ready_issues()

        if not issues:
            print("\n✅ No llm-ready issues found. Nothing to do!")
            return

        print(f"\nFound {len(issues)} llm-ready issues:")
        for i in issues[:args.max]:
            labels = [l["name"] for l in i.get("labels", [])]
            print(f"  #{i['number']}: {i['title']}")

        if len(issues) > args.max:
            print(f"  ... and {len(issues) - args.max} more (use --max to increase)")

        print("")

        solved = 0
        for issue in issues[:args.max]:
            if process_issue(issue, dry_run=args.dry_run, test_mode=args.test):
                solved += 1
            else:
                print(f"⚠️  Failed to process issue #{issue['number']}")

        print(f"\n{'='*60}")
        print(f"  Done! Solved {solved}/{min(len(issues), args.max)} issues")
        print(f"{'='*60}")


if __name__ == "__main__":
    main()
